import type { Metadata } from "next";
import { Lato } from "next/font/google"; // Import Lato
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "400", "700"], // Specify weights as needed
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
