// app/layout.tsx
import { Lato } from 'next/font/google';
import { Metadata } from 'next';
import './globals.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '400', '700'], // Specify weights as needed
  variable: '--font-lato',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
